version: '3'

services:
  nodejs-express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-express 
    volumes:
      - ./:/app
      - /app/node_modules 
    ports:
      - "3000:3000"

  db:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - /data/db
