version: '3'

services:
  nodejs-express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-express 
    volumes:
      - ./:/app
      - /app/node_modules 
    ports:
      - "3000:3000"
